### ISSUE TITLE
[Assigned to AlexRadulescu which I can't seem to assign the task to, thanks Github] Implement media section like in design

### ISSUE THREAD

**Issue by matzipan** [u-s-r/semneaza#18]
- Replace the media carousels with somethign that supports touch (you could reuse slick slider which is already included)
- Implement the entire design
- Ideally the images would be lazy loaded so that especially on mobile they do not affect the user's bandwidth
- Responsive design is a must

**Comment by alexradulescu** [comment]
Mine ;-)
